[font]
size = 9.0

[colors]
draw_bold_text_with_bright_colors = true

[font.normal]
family = "IosevkaTerm Nerd Font"

[general]
import = ["~/.config/srcery/srcery-terminal/alacritty/srcery_alacritty.toml"]
